version: '3.8'

services:
  db:
    image: postgres:15.2
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - db_data:${PGDATA}

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  db_data:
